### ISSUE TITLE
[BUG] unable to load stage2-core.ps1

### ISSUE THREAD

**Issue by ankushgoel27** [nettitude/PoshC2#104]
## Execution Environment:
**All of this must be filled in**
Data | Value
------ | ------
Full Posh version (all the text between the === at the top of the Implant Handler) | =============== PoshC2 v6.0 (0a32a9f 2020-05-03 13:12:05) ==============

OS | Linux linux 5.6.0-kali1-amd64 #1 SMP Debian 5.6.7-1kali1 (2020-05-12) x86_64 GNU/Linux

Using Docker/containerisation? No

## To Reproduce 
run the server and run the powershell payload on the victim. Victim connects but the shell never fully completes. It doesnt load stage2-core.ps1
## Expected behavior
i expected to get a full working shell

## Screenshots
![image](https://user-images.githubusercontent.com/10580970/82126761-55fd2f00-97cc-11ea-8da3-555c985eab1e.png)

**Comment by benpturner** [comment]
Hi, does the implant work at all?

**Comment by riskydissonance** [comment]
Also does this consistently happen? E.g. if you restart the server does it happen every time you execute the payload?

Will look into it in the mean time.

Thanks!

**Comment by ankushgoel27** [comment]
Yeah, it consistently happens for me.

**Comment by ankushgoel27** [comment]
hello, i dont see that error anymore but the stage2-core still doesnt load..only the agent checks in. thats it.
![image](https://user-images.githubusercontent.com/10580970/82453237-e5a52500-9acd-11ea-9e62-6780c8b2f03d.png)
any idea why its happening?

**Comment by riskydissonance** [comment]
Not sure what the issue is as we're not able to reproduce it, are you able to provide any information about the target host? E.g. Any AV/EDR products active, is constrained language mode active, what PowerShell versions are available, what version of Windows is it etc? We can then try and replicate the environment

You could also test from a test target VM if you're not already, check with Defender disabled etc that the simplest case works for your setup? Try the PowerShell one liner, but also e.g. Posh64.exe or a Sharp Implant?

You can also try running the server using Docker and/or re-running the Install script and paying close attention to the log for any errors. Could be something didn't install correctly on your server.

**Comment by ankushgoel27** [comment]
was able to solve this issue. was on a UDP vpn. switched to TCP and it worked fine.

**Comment by riskydissonance** [comment]
Good to know, thanks!
