### ISSUE TITLE
Sharpsocks error !

### ISSUE THREAD

**Issue by vardanbansal** [nettitude/PoshC2#110]
I updated poshc2 framework and I got error again and again when I ran posh-server I got the below error..

Error with sharpsocks or old implant connection - is sharpsocks is running /usersync/tradedesk/***************

Same goes this again and again..

**Comment by riskydissonance** [comment]
It's because you have an implant with an old key running which is trying to connect back, it's successfully connecting but cannot be decrypted. When you updated you must have removed the old project directory with the key.

Just kill the implant process on the target to get it stop beaconing.

If you can't do that, you can run posh on a different port or comment out the line which prints the message in the code until the guilty implant dies.
