### ISSUE TITLE
[help] Unknown C2 comms incoming (Could be old implant or sharpsocks)

### ISSUE THREAD

**Issue by donjuanme** [nettitude/PoshC2#207]
hi

how can i attach to this implant ?

Unknown C2 comms incoming (Could be old implant or sharpsocks)

is there anything i can do to connect to it. its not listed for me to interact with.

**Comment by Console** [comment]
You can't. the C2 server does not know the encryption key for the incoming C2 traffic.

You either: 
* have something that is probably an old implant beaconing into your server and the server cannot decrypt it because it does not know the encryption key for that implant.
* or it could be someone simply reaching the web server of your poshc2 server and the server is attempting to decrypt the traffic but cannot because it is not valid C2 traffic.

**Comment by donjuanme** [comment]
yes i am aware what it is. my question was there anyway to accept the
connection of the old beacon ?

**Comment by Console** [comment]
if you still have the project folder, use posh-project -s <project-name> to switch back to the old project.

**Comment by riskydissonance** [comment]
Hey @donjuanme as @Console has said the only way to accept the only beacon is to use the old project, as the comms URLs, encryption key etc all need to be correct in order to accept the implant and the key at least is unique per project. If you don't have that then there is no feasible way as you can't decrypt the comms.
